[project]
name = "repl-nix-db-punch"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.8"
dependencies = [
    "flask>=3.0.3",
    "flask-cors>=5.0.0",
    "requests>=2.32.3",
]
